### PR TITLE
Adding Alertbar UI component

### PR DESCRIPTION
**Pull request by vitalbone**

### CODE REVIEW

**Comment by JedWatson** [comment]
:+1: Thanks @vitalbone!

**Comment by dcousens** [comment]
@vitalbone / @JedWatson - any chance we can get a image of what this is, and what it offers over the native `alert`?  
Or is it the notification bar?

@jossmac can you please ACK (I know its already been merged).

**Comment by vitalbone** [comment]
@dcousens my bad - first merge request. Converted 'alertbar' from a CSS class to a UI component, at @jossmac's request.

alertbar

**Comment by jossmac** [comment]
@dcousens I oversaw this implementation

**Comment by dcousens** [comment]
Tested and works well.  +1

**Pull request merged**
