### PR TITLE
updated gulp-less version to 3.0.1

### PR DESCRIPTION
**Pull request by knowbody**
Fix to issue [#44](https://github.com/JedWatson/touchstonejs/issues/44)

### CODE REVIEW

**Comment by dcousens** [comment]
Thanks @knowbody :)

**Comment by knowbody** [comment]
haven't done much, happy to contribute. What's urgent at the moment?

**Comment by morenoh149** [comment]
@knowbody anything on the roadmap https://github.com/JedWatson/touchstonejs/labels/roadmap or bugs

**Comment by knowbody** [comment]
it will be great, whenever you have a time, to `npm publish` it, so the error won't appear on `touchstone-starter`

**Pull request merged**
